global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ingest'
    static_configs:
      - targets: ['ingest:8081']
  
  - job_name: 'bars'
    static_configs:
      - targets: ['bars:8083']
  
  - job_name: 'indicator'
    static_configs:
      - targets: ['indicator:8085']
  
  - job_name: 'scanner'
    static_configs:
      - targets: ['scanner:8087']
  
  - job_name: 'ws-gateway'
    static_configs:
      - targets: ['ws-gateway:8089']
  
  - job_name: 'api'
    static_configs:
      - targets: ['api:8091']

