apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stock-scanner

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml.example
  - ingest-deployment.yaml
  - bars-deployment.yaml
  - indicator-deployment.yaml
  - scanner-deployment.yaml
  - alert-deployment.yaml
  - ws-gateway-deployment.yaml
  - api-deployment.yaml
  - services.yaml
  - hpa.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: stock-scanner
  app.kubernetes.io/part-of: stock-scanner

